# Generated by Django 4.0.4 on 2022-05-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='daily_rate',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='number_in_stock',
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
